import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import dynamic from 'next/dynamic'
import Header from "../components/header"
const Footer = dynamic(() => import("../components/Footer"), {
  ssr: false
})
export default function Home() {


  return (
    
    <div>
      <Head>
        <title>Propsearch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="main">

      </main>
<div class="elfsight-app-d195f209-3314-47fc-829b-b568adcc1731"></div>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <Footer/>
      <script src="https://apps.elfsight.com/p/platform.js" defer></script>
    </div>

  )
}
